FROM python:3.11-slim

RUN pip install --no-cache-dir dbt-core dbt-trino

WORKDIR /usr/app/dbt

# profiles.yml layihə qovluğunun daxilində saxlanılır (DBT_PROFILES_DIR ilə)
ENV DBT_PROFILES_DIR=/usr/app/dbt

ENTRYPOINT ["dbt"]
CMD ["--help"]
